### ISSUE TITLE
Kill / stop previous session when switching sessions

### ISSUE THREAD

**Issue by piersolenski** [danielpieper/telescope-tmuxinator.nvim#1]
Hey! Really glad I came across this extension! I was wondering if it was possible to actually stop the previous session when switching rather than leaving it running and detached? Thanks!

**Comment by danielpieper** [comment]
Hello, great that you find this extension useful.

Currently you can stop the previous session by searching for it's name and pressing Ctrl + x
But adding another hotkey to allow switching and stopping sessions seams reasonable.
I'll look into it!

**Comment by piersolenski** [comment]
That would be really great... as often I want to tap into the `on_project_stop` hooks to stop projects from running on the same ports!

**Comment by danielpieper** [comment]
Hey @piersolenski, i've added the feature.
Please tell me if it works on your machine :)

**Comment by piersolenski** [comment]
Hey @danielpieper! Thanks for implementing this. It does indeed seem to stop the session, however, I think unless I can achieve my intended behaviour through a tmuxinator config, I'd actually want to kill the session rather than stop it. 

For example, most of my current projects look like this:

```
name: Example

windows:
  - Frontend:
      root: ~/Projects/example-frontend
      panes:
        - vim
  - Backend:
      root: ~/Projects/example-backend
      panes:
        - vim

  - Server:
      layout: even-vertical
      panes:
        - Frontend:
            - cd ~/Projects/example-frontend
            - npm run dev
        - Backend:
            - cd ~/Projects/example-backend
            - yarn dev

on_project_stop: kill-port 3000 3333

# OR
# on_project_exit: kill-port 3000 3333
```

Thus when I kill a session and start a new one, it will recreate this environment each time, but crucially also kill anything running on common ports and run my npm commands.

Comparatively, when I stop a session and then restart it, it restores the previous session and doesn't restart the servers.

The functionality you've added does get me a step closer, as I can now kill the ports, however, it still doesn't allow the servers to be restarted.

tmuxinator has a `on_project_start` hook but I don't think it allows you to use it on a per pane basis, otherwise, I could use that.

tmuxinator also doesn't offer a `kill-session` command, therefore I think what is actually needed to achieve this functionality is simply `tmux kill-session`. I tried changing it locally it didn't seem to work, however, I'm just getting started with neovim + lua so I might have missed something...

Finally, it would be awesome to be able to set the default behaviour in the config, as I only ever really want to use the `C-v` behaviour!

Let me know your thoughts, I understand if this is outside of the scope of the plugin!
